# .github/workflows/docker-image-tagging.yml
name: Docker Tag and Push

on:
  push:
    branches:
      - master

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Create and Push Git Tag
      - name: Create and Push Git Tag
        id: tag
        run: |
          TAG_NAME="v$(date +%Y%m%d%H%M%S)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Step 2: Build the Docker Image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t fateseph/microservices:$TAG_NAME .

      # Step 3: Push Docker Image to Registry
      - name: Push Docker Image
        run: |
          docker push fateseph/microservices:$TAG_NAME
