# .github/workflows/docker-image-tagging.yml
name: Docker Tag and Push

on:
  push:
    branches:
      - master

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set Image Tag Name
      - name: Set Image Tag
        run: echo "TAG_NAME=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          IMAGE_NAME="fateseph/microservices"
          docker build -t $IMAGE_NAME:${{ env.TAG_NAME }} -f ./Microservices/Dockerfile Microservices

      # Step 5: Push Docker Image to Registry
      - name: Push Docker Image
        run: |
          IMAGE_NAME="fateseph/microservices"
          docker push $IMAGE_NAME:${{ env.TAG_NAME }}
